# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160514_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
