# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
