# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 5, 12, 19, 19, 41, 917408, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
