# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_photos',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
